const WA='4915752418921';
const dishImages={
  '1':'assets/menu-pdf/p02-12.jpeg','2':'assets/menu-pdf/p02-03.jpeg','3':'assets/menu-pdf/p02-07.jpeg','4':'assets/menu-pdf/p02-11.jpeg','5':'assets/menu-pdf/p02-02.jpeg','6':'assets/menu-pdf/p02-09.jpeg','7':'assets/menu-pdf/p02-01.jpeg','8':'assets/menu-pdf/p02-08.jpeg','10':'assets/menu-pdf/p02-04.jpeg',
  '35':'assets/menu-pdf/p03-03.jpeg','36':'assets/menu-pdf/p03-02.jpeg','37':'assets/menu-pdf/p03-04.jpeg','38':'assets/menu-pdf/p03-01.jpeg','39':'assets/menu-pdf/p03-06.jpeg',
  '40':'assets/menu-pdf/p04-06.jpeg','41':'assets/menu-pdf/p04-05.jpeg','44':'assets/menu-pdf/p04-04.jpeg','45':'assets/menu-pdf/p04-03.jpeg','46':'assets/menu-pdf/p04-02.jpeg','47':'assets/menu-pdf/p04-01.jpeg','61':'assets/menu-pdf/p04-07.jpeg',
  '70':'assets/menu-pdf/p05-16.jpeg','71':'assets/menu-pdf/p05-15.jpeg'
};
const photoFor=(_category,dish)=>dishImages[dish[0]];
const menu=[
['Vorspeisen',[['1','KHOAI LANG CHIEN','Süßkartoffeln','',3.5],['2','SALMON YAKI','Gegrillter Lachs, Spinat und Spezial-Soße','4',8.4],['3','EDAMAME','Knackige japanische Bohnen','6',3.5],['4','EBI YAKI','Gegrillte Garnelen mit Spargel, Spinat und Spezial-Soße','2',8.4],['5','PRAWN TORNADO','3 Stk. gebackene Garnelen, umwickelt mit Kartoffelspirale','2',5],['6','TUNA YAKI','Angebratener Thunfisch, Spinat und Spezial-Soße','4',8],['7','SPRING ROLL','5 vegetarische Mini-Frühlingsrollen','1a,6',4],['8','YAKITORI','3 Stk. gegrillte Hähnchenspieße','',5],['10','GOI CUON TOM','2 Stk. Sommerrollen mit Garnelen, Salat, Kräutern und Reisnudeln','2,3',5],['11','GOI CUON GA','2 Stk. Sommerrollen mit Hühnerfleisch, Salat, Kräutern und Reisnudeln','3',5],['13','WAN TAN CHIEN','5 Stk. Wantan-Teig mit Huhn und Garnelen','1',5.4],['14','NEM','2 Frühlingsrollen mit Fleisch','3',5]]],
['Suppen',[['35','SAKE SUPPE','Lachssuppe mit Dill, Seetang und Frühlingszwiebeln','5',4.4],['37','MISO SUPPE','Sojabohnenpasta mit Seetang, Frühlingszwiebeln und Tofu','6',3.5],['36','EBI SUPPE','Garnelen, Spargel, Champignons, Zwiebeln und Kräuter','2',4.4],['38','SUA DUA TOM','Kokosmilch, Garnelen, Champignons, Tomaten und Kräuter','2',3.9],['39','SAM SAM SPECIAL','Jakobsmuschel, Garnelen, Spargel, Pak Choi und Kräuter','2,14',4.9]]],
['Maki · 6 Stück',[['40','SAKE AVOCADO','Lachs, Avocado','4',4],['41','TEKKA','Thunfisch','4',4],['42','SAKE KAPPA','Lachs, Gurke','4',4],['43','KAPPA','Gurke','',3.3],['44','AVOCADO','Avocado','',3.3],['45','TAMAGO','Japanisches Omelett','3',3.3],['46','EBI AVOCADO','Garnelen, Avocado','2',4.4],['47','TEKKA SPICY','Scharfer Thunfisch, Lauch','4',4.4],['48','KANI SPECIAL','Krebsfleisch, Mayonnaise','2,3',4.4],['49','TUNA','Gekochter Thunfisch, Lauch, Mayo, Chili','3,4',4.4],['50','TORI KARAAGE','Hähnchenstreifen','',4.4],['51','CALIFORNIA','Surimi, Avocado','Srm',4],['61','FUTO VEGGIE','Verschiedenes Gemüse, Sesam','11',6.5],['65','FUTO BIG ROLL','Lachs, verschiedenes Gemüse','4',7]]],
['Inside Out · 8 Stück',[['70','SAKE I.O.','Lachs, Avocado','4',7.9],['71','MAGURO I.O.','Thunfisch, Gurke','4',7.9],['72','VEGGIE I.O.','Kürbis, Rettich, Avocado, Sesam','14',7.5],['73','EBI I.O.','Garnelen, Avocado','2',7.9],['74','MAGURO SPICY I.O.','Scharfer Thunfisch, Gurke, Lauch','4',7.9],['75','CALIFORNIA I.O.','Krebsfleischimitat, Avocado','Srm',6.9],['76','SALMON SKIN I.O.','Lachshaut, Gurke, Aal','4',7.9],['77','EBI SPICY I.O.','Scharfe Garnelen, Gurke, Lauch','2',7.9],['78','SAKE SPICY I.O.','Scharfer Lachs, Gurke, Lauch','4',7.5],['79','RUCOLA KAPPA I.O.','Rucola, Gurke, Frischkäse, Sesam','7,11',6.9],['80','KANI SPECIAL I.O.','Krebsfleisch, Avocado, Mayonnaise','2,3',7.5],['85','EBI TEMPURA I.O.','Panierte Garnelen, Frischkäse, Gurke','1a,2,3,7',9.5]]],
['Crunchy I-O Rolls · 8 Stück',[['90','SAKE CRUNCHY','Lachs, Avocado, Frischkäse','1a,3,7',8.2],['91','SALMON TEMPURA CRUNCHY','Panierter Lachs, Frischkäse','1a,3,4,7',9.5],['92','TUNA CRUNCHY','Gekochter scharfer Thunfisch, Mayonnaise, Gurke','1a,3,4',7.9],['93','LIAM CRUNCHY','Panierte Hähnchenstreifen, Frischkäse, Gurke','1a,3,7',8.2],['94','SKIN CRUNCHY','Gegrillte Lachshaut, Gurke, Aal','1a,3,4',8.2],['95','EBI CRUNCHY','Scharfe Garnelen, Lauch, Gurke','1a,2,3',7.9],['96','KRABBEN CRUNCHY','Krebsfleisch, Mayonnaise, Avocado','1a,2,3',7.9],['98','MAGURO CRUNCHY','Scharfer Thunfisch, Lauch, Gurke','1a,3,4',8.2]]],
['Nigiri · 2 Stück',[['110','SAKE','Lachs','4',4],['111','MAGURO','Thunfisch','4',5.4],['112','MUTZU','Butterfisch','4a',4],['113','EBI','Garnelen','2',5],['114','IKA','Tintenfisch','14',5],['115','TAMAGO','Omelett','3',4.4],['116','INARI','Tofu','6',3.5],['117','AVOCADO','Avocado','',3.5]]],
['Sushi-Menüs',[['M1','MENÜ 1','2 Sake Nigiri, 8 Sake Rolls','',13.5],['M2','MENÜ 2','8 Avocado I.O., 8 Sake Crunchy I.O., 8 California I.O.','',19.9],['M3','MENÜ 3','6 Mango Maki, 6 Kappa Maki, 8 Avocado Rolls','',12.5],['M4','MENÜ 4','8 Sake I.O., 4 Taiko Rolls, 3 Nigiri: Sake, Maguro, Ebi','',19],['M5','MENÜ 5','6 Sake Maki, 4 Kyoto Rolls, 4 Tazuna Rolls, 2 Nigiri: Sake, Ebi','',21],['M6','MENÜ 6','8 Sake Rolls, 8 Ebi Rolls, 8 Jenny Rolls','',20.9],['M7','MENÜ 7','6 New York Rolls, 6 Atlantic Rolls, 6 Fuji Rolls','',25],['M8','MENÜ 8','6 Sake Avocado Maki, 6 California Maki, 8 Sake Crunchy I.O., 8 Kani Special I.O., 8 Avocado Rolls, 6 New York Rolls, 4 Nigiri','',45],['M9','MENÜ 9','6 Avocado Maki, 8 Kappa Rolls, 2 Nigiri: Tamago, Inari','',12],['M10','MENÜ 10','8 Tuna Crunchy I.O., 4 Fuji Yama Rolls, 4 Black Tiger Rolls, 2 Sake Nigiri Aburi','',25],['M11','MENÜ 11','2 Sake Nigiri Aburi, 2 Maguro Nigiri Aburi, 2 Ebi Nigiri, 2 Avocado Nigiri','',15],['M12','MENÜ 12','Großes Menü mit Maki, Inside Out, Rolls und 8 Nigiri','',68]]],
['Teriyaki',[['300','SALMON TERIYAKI','Gegrillter Lachs mit verschiedenem Gemüse','4',16.9],['301','TUNA TERIYAKI','Angebratener Thunfisch mit verschiedenem Gemüse','4',17.9],['302','BEEF TERIYAKI','Mariniertes Rindfleisch mit verschiedenem Gemüse','',14.9],['303','SQUID TERIYAKI','Gegrillter Tintenfisch mit verschiedenem Gemüse','14',17.9],['304','HOTATEGAI TERIYAKI','Gegrillte Jakobsmuscheln mit verschiedenem Gemüse','14',17.9],['306','CHICKEN TERIYAKI','Gegrilltes Hühnerfleisch mit verschiedenem Gemüse','',13.9],['307','TORI TERIYAKI','Gebackenes Hähnchenbrustfilet','',12.9],['308','DUCK TERIYAKI','Gegrillte Ente mit verschiedenem Gemüse','',15.9]]],
['Poke Bowls',[['490','BUDDHA POKE BOWL','Mit Tofu','6',11.9],['491','YAKITORI POKE BOWL','Mit süßem Huhn am Spieß','',12.9],['492','BEEF POKE BOWL','Mit mariniertem Rindfleisch','',13.5],['493','CRISPY CHICKEN POKE BOWL','Mit paniertem Hähnchen','1',13.5],['494','GRILL CHICKEN POKE BOWL','Mit gegrilltem Hähnchenbrustfilet','',13.5],['495','SAKE POKE BOWL','Mit rohem Lachs','4',13.9],['496','TUNA POKE BOWL','Mit rohem Thunfisch','4',15.9]]],
['Desserts',[['620','DRAGON BALL','4 Stk. gefüllt mit süßen Bohnen','',4],['621','MOCHI','Reiskuchen mit roten Bohnen','',4],['622','LUCKY EGG','4 Stk. gefüllt mit Vanille','',4],['623','BANANIFLIRT','Gebackene Banane mit Spezialsoße','',4],['624','APFEL FLIRT','Mit Spezialsoße','',4],['625','ANANAS FLIRT','Mit Spezialsoße','',4]]],
['Getränke',[['700','COLA','0,3 l','K,F,S',3.4],['701','COLA LIGHT','0,3 l','K,F,S,Su',3.4],['702','FANTA','0,3 l','F,S',3.4],['703','SPEZI','0,3 l','A,F,S',3.4],['704','SPRITE','0,3 l','',3.4],['710','MANGO SAFT/SCHORLE','0,3 l','',3.8],['720','GRÜN-TEE','0,3 l','',4],['730','MANGO-LASSI','0,4 l','7',5.9],['740','SAPPORO','0,33 l','1',3.8],['741','ASAHI','0,33 l','1',3.8],['760','PINOT GRIGIO','0,2 l / Flasche 0,75 l','12',5.5],['770','APEROL SPRITZ','Prosecco, Aperol, Soda, Orange','12',7.2]]]
];
const money=n=>n.toLocaleString('de-DE',{style:'currency',currency:'EUR'}); let cart={};
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function renderMenu(){const cats=document.querySelector('#categories'),select=document.querySelector('#category-select'),list=document.querySelector('#menu-list');cats.innerHTML=menu.map((c,i)=>`<button class="${i===0?'active':''}" data-target="${slug(c[0])}">${c[0]}</button>`).join('');select.innerHTML=menu.map(c=>`<option value="${slug(c[0])}">${c[0]}</option>`).join('');list.innerHTML=menu.map(([cat,items])=>`<section class="menu-category" id="${slug(cat)}" data-category="${slug(cat)}"><h3>${cat}</h3><div class="dish-grid">${items.map((d,i)=>{const photo=photoFor(cat,d,i);return `<article class="dish ${photo?'has-photo':''}" data-search="${`${d[0]} ${d[1]} ${d[2]}`.toLowerCase()}">${photo?`<img class="dish-photo" src="${photo}" alt="Gericht ${d[1]}" loading="lazy" decoding="async">`:''}<div><span class="nr">Nr. ${d[0]}</span><h4>${d[1]}</h4></div><strong class="price">${money(d[4])}</strong><p>${d[2]}</p><span class="allergy">${d[3]?`Allergene: ${d[3]}`:'Allergene: –'}</span><button data-add="${d[0]}">Bestellen</button></article>`}).join('')}</div></section>`).join('');}
function findDish(id){for(const [,items] of menu){const d=items.find(x=>x[0]===id);if(d)return d}}
function updateCart(){const box=document.querySelector('#cart-items'),entries=Object.entries(cart);box.innerHTML=entries.length?entries.map(([id,q])=>{const d=findDish(id);return `<div class="cart-line"><span>${q}× Nr. ${d[0]} ${d[1]}</span><b>${money(d[4]*q)}</b><div class="qty"><button data-qty="${id}" data-delta="-1">−</button><span>${q}</span><button data-qty="${id}" data-delta="1">+</button></div></div>`}).join(''):'<p class="empty">Noch nichts ausgewählt.</p>';const total=entries.reduce((s,[id,q])=>s+findDish(id)[4]*q,0);document.querySelector('#cart-total').textContent=money(total);document.querySelector('#cart-count').textContent=entries.reduce((s,[,q])=>s+q,0)}
renderMenu();
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){cart[add.dataset.add]=(cart[add.dataset.add]||0)+1;updateCart()}const qty=e.target.closest('[data-qty]');if(qty){cart[qty.dataset.qty]=(cart[qty.dataset.qty]||0)+Number(qty.dataset.delta);if(cart[qty.dataset.qty]<=0)delete cart[qty.dataset.qty];updateCart()}const target=e.target.closest('[data-target]');if(target){document.querySelectorAll('.category-nav button').forEach(x=>x.classList.remove('active'));target.classList.add('active');document.getElementById(target.dataset.target).scrollIntoView()}if(e.target.closest('.menu-toggle')){const n=document.querySelector('#nav');n.classList.toggle('open');e.target.closest('.menu-toggle').setAttribute('aria-expanded',n.classList.contains('open'))}if(e.target.closest('#cart-fab'))document.querySelector('#cart').classList.add('open');if(e.target.closest('.cart-close'))document.querySelector('#cart').classList.remove('open');if(e.target.closest('.gallery-item'))document.querySelector('#lightbox').showModal();if(e.target.closest('#lightbox button'))document.querySelector('#lightbox').close();const legal=e.target.closest('[data-modal]');if(legal){document.querySelector('#legal-content').innerHTML=legal.dataset.modal==='impressum'?'<h2>Impressum</h2><p><b>Jenny Sam Sushi</b><br>Pferdestraße 33<br>14913 Jüterbog<br>Telefon: 03372 4423033<br>E-Mail: anhdungle2982@gmail.com</p><p>Inhaltlich verantwortlich: Betreiber von Jenny Sam Sushi.</p>':'<h2>Datenschutz</h2><p>Diese statische Website setzt keine Analyse-Cookies. Bei Nutzung von WhatsApp, Google Maps, Telefon oder E-Mail gelten die Datenschutzbestimmungen des jeweiligen Anbieters. Formulardaten werden ausschließlich lokal im Browser verarbeitet und als von Ihnen ausgelöste WhatsApp-Nachricht vorbereitet.</p>';document.querySelector('#legal').showModal()}if(e.target.closest('.dialog-close'))document.querySelector('#legal').close()});
document.querySelector('#send-order').addEventListener('click',()=>{const entries=Object.entries(cart);if(!entries.length){alert('Bitte wählen Sie zuerst ein Gericht.');return}const total=entries.reduce((s,[id,q])=>s+findDish(id)[4]*q,0),lines=entries.map(([id,q],i)=>{const d=findDish(id);return `${i+1}. ${q}x Nr. ${d[0]} ${d[1]} – ${money(d[4]*q)}`});const note=document.querySelector('#note').value.trim();const text=`Hallo Jenny Sam, ich möchte bestellen:\n\n${lines.join('\n')}\n\nGesamt: ${money(total)}${note?`\n\nAnmerkung: ${note}`:''}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,'_blank','noopener')});
document.querySelector('#reservation-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),text=`Hallo Jenny Sam, ich möchte gerne einen Tisch reservieren.\n\nName: ${f.get('name')}\nTelefonnummer: ${f.get('phone')}\nDatum: ${f.get('date')}\nUhrzeit: ${f.get('time')}\nPersonen: ${f.get('people')}\nNachricht: ${f.get('message')||'-'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,'_blank','noopener')});
document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('#nav').classList.remove('open')));

// Motion system: one staged entrance, purposeful scroll guidance and tactile feedback.
const root=document.documentElement,header=document.querySelector('.site-header'),hero=document.querySelector('.hero');
const updateScroll=()=>{const max=document.documentElement.scrollHeight-innerHeight;root.style.setProperty('--scroll',max>0?scrollY/max:0);header.classList.toggle('scrolled',scrollY>32)};
addEventListener('scroll',updateScroll,{passive:true});updateScroll();
if(matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches){hero.addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*8,y=(e.clientY/innerHeight-.5)*6;hero.style.setProperty('--hero-x',`${x}px`);hero.style.setProperty('--hero-y',`${y}px`)})}
const revealTargets=document.querySelectorAll('.intro,.section-head,.menu-title,.reservation>div,.reservation form,.contact-info,.contact iframe,.footer-grid');
revealTargets.forEach(el=>el.classList.add('motion-reveal'));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.14,rootMargin:'0px 0px -7%'});
revealTargets.forEach(el=>revealObserver.observe(el));
const categoryObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('in-view')}),{threshold:.08});
document.querySelectorAll('.menu-category').forEach(el=>categoryObserver.observe(el));
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const fab=document.querySelector('#cart-fab'),dish=add.closest('.dish');fab.classList.remove('bump');dish?.classList.remove('just-added');requestAnimationFrame(()=>{fab.classList.add('bump');dish?.classList.add('just-added')});const old=add.textContent;add.textContent='Hinzugefügt ✓';add.classList.add('is-confirmed');setTimeout(()=>{add.textContent=old;add.classList.remove('is-confirmed');dish?.classList.remove('just-added')},900)}});
const searchInput=document.querySelector('#menu-search'),categorySelect=document.querySelector('#category-select'),menuResult=document.querySelector('#menu-result');
function filterMenu(){const query=searchInput.value.trim().toLowerCase(),category=categorySelect.value;let visible=0;document.querySelectorAll('.menu-category').forEach(section=>{const active=section.dataset.category===category;section.querySelectorAll('.dish').forEach(dish=>{const show=active&&(!query||dish.dataset.search.includes(query));dish.hidden=!show;if(show)visible++});section.hidden=!active});menuResult.textContent=visible===1?'1 Ergebnis':`${visible} Ergebnisse`;}
searchInput.addEventListener('input',filterMenu);categorySelect.addEventListener('change',()=>{searchInput.value='';document.querySelectorAll('.category-nav button').forEach(button=>button.classList.toggle('active',button.dataset.target===categorySelect.value));filterMenu()});
document.querySelector('#categories').addEventListener('click',e=>{const button=e.target.closest('[data-target]');if(!button)return;categorySelect.value=button.dataset.target;searchInput.value='';filterMenu()});
categorySelect.value=slug(menu[0][0]);filterMenu();

// A restrained depth layer for food photography on precise pointers.
if(matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches){
  document.querySelectorAll('.special').forEach(card=>{
    card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--tilt-x',`${(-y*2.2).toFixed(2)}deg`);card.style.setProperty('--tilt-y',`${(x*2.2).toFixed(2)}deg`);card.style.setProperty('--light-x',`${((x+.5)*100).toFixed(0)}%`);card.style.setProperty('--light-y',`${((y+.5)*100).toFixed(0)}%`)});
    card.addEventListener('pointerleave',()=>{card.style.removeProperty('--tilt-x');card.style.removeProperty('--tilt-y')});
  });
}

// Keep orientation visible while browsing long pages.
const pageSections=[...document.querySelectorAll('main section[id]')],navLinks=[...document.querySelectorAll('#nav a[href^="#"]')];
const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;navLinks.forEach(link=>link.classList.toggle('is-current',link.getAttribute('href')===`#${entry.target.id}`))}),{rootMargin:'-28% 0px -62%',threshold:0});
pageSections.forEach(section=>navObserver.observe(section));

// Gallery items arrive as one composed sequence, not repeated section fades.
const gallery=document.querySelector('.gallery-grid');
if(gallery){const galleryObserver=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){gallery.classList.add('is-visible');galleryObserver.disconnect()}},{threshold:.18});galleryObserver.observe(gallery)}
